seu_nome=str(input("digite nome: "))
num_tel=str(input("digite seu telefone: "))
email=str(input("digite seu e-mail: "))
endereco=str(input("digite seu endereço: "))
sexo=str(input("digite seu sexo: "))
salario=str(input("digite seu salário: "))
idade=str(input("digite sua idade: "))

print("nome: ",seu_nome)
print("número de telefone",num_tel)
print("e-mail: ",email)
print("endereço: ",endereco)
print("sexo: ",sexo)
print("salaŕio: ",salario)
print("idade",idade)